### ISSUE TITLE
The code of minist

### ISSUE THREAD

**Issue by Lxy85** [Sophia-Cristina/My-Noob-Headers#1]
Hello, I saw your question about the data set on OpenNN's github website. Can you share your code, thank you.

**Comment by Sophia-Cristina** [comment]
Ohh, i see, this one?:
https://github.com/Artelnics/opennn/issues/150

I have changed part of that code, however, long time i don't mess with OpenNN since i think it can't do GAN, so i would have to do everything manually. I still think i may use their convolution and other layers...
Consequently, i'm not even sure if my code still works...

The code is a mess, and it is almost a "hello world" of it... Also, i'm still a "total" noob on OpenNN, i saw you opened an issue there too, however, i don't know how to deal with the dataset and Tensor object.
I hope you find your solution, in my case it was just that the DataSet, for some reason, needs at least TWO inputs, and when i was using only one input for test, it was crashing...

Anyway, my code is below, i deleted some headers which aren't useful for you, however, i'm going to add some of the functions i had inside it being used:

```
// CREATE A DATASET FROM PATHS FOR A RANGE OF IMAGES BASED ON THE SIZE OF A VECTOR OF TARGETS:
// Create a bunch of images like 'image0.png', write 'Prefix = image'.
// It always begins at '0', if you want a specific image, skew this code.
// Target vector size must be <= amount of available images at path.
void MakeDataSetRGBLine(string Prefix, vector<int> Target)
{
	ofstream oPrint("DATA.csv"); if (!oPrint.is_open()) { cout << "!!! Arquivo não foi aberto. !!!" << endl; }
	else
	{
		if (Target.size() > 0)
		{
			for (int Index = 0; Index < Target.size(); ++Index)
			{
				CImg<unsigned char> BMP(Str2Char(Prefix + to_string(Index) + ".png").data()); // Open imagem file. Str2Char is an abandoned function i made to make easier by writing everything between '(' and ')' without creating another string variable, it in fact returns a vector<unsigned char>
				vector<Point3DFlt> Image = BitmapRGBMatrix(BMP); // FLATTEN RGB values, this method just go from line by line of the image and push back the RGB values to the vector
				oPrint << Target[Index]; for (int n = 0; n < Image.size(); ++n) { oPrint << "," << Image[n].x << "," << Image[n].y << "," << Image[n].z; }
				oPrint << endl;
			}
		}
		else { oPrint << "'Target' vector is empty!\n"; std::cout << "'Target' vector is empty!\n"; }
	}
	oPrint.close();
}
```

---

```
void Configure(OpenNN::NeuralNetwork& NN, const Vector<size_t> InputDimensions, const size_t outputs_number)
{
	// Scaling layer

	ScalingLayer* scaling_layer = new ScalingLayer(InputDimensions);
	NN.add_layer(scaling_layer);

	const Vector<size_t> scaling_layer_outputs_dimensions = scaling_layer->get_outputs_dimensions();

	// Convolutional layer 1

	ConvolutionalLayer* convolutional_layer_1 = new ConvolutionalLayer(scaling_layer_outputs_dimensions, { 8, 5, 5 });
	NN.add_layer(convolutional_layer_1);

	const Vector<size_t> convolutional_layer_1_outputs_dimensions = convolutional_layer_1->get_outputs_dimensions();

	// Pooling layer 1

	PoolingLayer* pooling_layer_1 = new PoolingLayer(convolutional_layer_1_outputs_dimensions);
	NN.add_layer(pooling_layer_1);

	const Vector<size_t> pooling_layer_1_outputs_dimensions = pooling_layer_1->get_outputs_dimensions();

	// Convolutional layer 2

	ConvolutionalLayer* convolutional_layer_2 = new ConvolutionalLayer(pooling_layer_1_outputs_dimensions, { 4, 3, 3 });
	NN.add_layer(convolutional_layer_2);

	const Vector<size_t> convolutional_layer_2_outputs_dimensions = convolutional_layer_2->get_outputs_dimensions();

	// Pooling layer 2

	PoolingLayer* pooling_layer_2 = new PoolingLayer(convolutional_layer_2_outputs_dimensions);
	NN.add_layer(pooling_layer_2);

	const Vector<size_t> pooling_layer_2_outputs_dimensions = pooling_layer_2->get_outputs_dimensions();

	// Convolutional layer 3

	ConvolutionalLayer* convolutional_layer_3 = new ConvolutionalLayer(pooling_layer_2_outputs_dimensions, { 2, 3, 3 });
	NN.add_layer(convolutional_layer_3);

	const Vector<size_t> convolutional_layer_3_outputs_dimensions = convolutional_layer_3->get_outputs_dimensions();

	// Pooling layer 3

	PoolingLayer* pooling_layer_3 = new PoolingLayer(convolutional_layer_3_outputs_dimensions);
	NN.add_layer(pooling_layer_3);

	const Vector<size_t> pooling_layer_3_outputs_dimensions = pooling_layer_3->get_outputs_dimensions();

	// Perceptron layer

	PerceptronLayer* perceptron_layer = new PerceptronLayer(pooling_layer_3_outputs_dimensions.calculate_product(), 18);
	NN.add_layer(perceptron_layer);

	const size_t perceptron_layer_outputs = perceptron_layer->get_neurons_number();

	// Probabilistic layer

	ProbabilisticLayer* probabilistic_layer = new ProbabilisticLayer(perceptron_layer_outputs, outputs_number);
	NN.add_layer(probabilistic_layer);

	NN.print_summary();
}

```
---

```
// CImg to help me:
#include "ysxCImg.h" // my header, on this repository by the way
#include "ysxPrint.h"

// System includes
#include <math.h>
#include <time.h>

// OpenNN includes
#include "../../opennn/opennn.h"

using namespace std;
using namespace OpenNN;

int main()
{
    cout << "OpenNN. Attempt to make a GAN." << endl;

    // MAKE DATA:
    CImg<unsigned char> IMG("TestImages/Number1.png"); // 10x10 image; CImg is a pretty simple image header: http://cimg.eu/
    vector<int> Targets;
    for (int n = 0; n < 11; ++n) { Targets.push_back(1); } // This looks lame, but it is just for the test
    MakeDataSetRGBLine("TestImages/Number", Targets);
    size_t Size = IMG.width() * IMG.height() * 3; // Size for inputs, not for image
    size_t Width = IMG.width() * 3, Height = IMG.height() * 3; // Width for inputs, not for image
    //MakeDataSetRGBMatrix(RGB, 10, 0);

    // OPEN DATA:
    DataSet data_set("DATA.csv", ',', false);

    data_set.set_input();
    data_set.set_column_use(0, OpenNN::DataSet::VariableUse::Target);
    data_set.numeric_to_categorical(0);
    data_set.set_batch_instances_number(5);

    const Vector<size_t> inputs_dimensions({ 1, Width, Height }); // It was { 1, 10, 10 }, but as i noticed the MNIST example don't counts all channels, i'm using RGB
    const Vector<size_t> targets_dimensions({ 10 }); // From '0 - 9', that is 10 targets
    data_set.set_input_variables_dimensions(inputs_dimensions);
    data_set.set_target_variables_dimensions(targets_dimensions);

    const size_t total_instances = 10; // Change it for the number of instances, i have 10 images in my folder
    data_set.set_instances_uses((Vector<string>(total_instances, "Training").assemble(Vector<string>(Size - total_instances, "Unused"))));
    data_set.split_instances_random(0.75, 0, 0.25);

    // ####### NN #######

    NeuralNetwork NN;
    Configure(NN, inputs_dimensions, 10);
      
    // #####################
    // #####################
    // #####################
    int NADA; cin >> NADA; // Ignore, just a lazy ass trick to pause the terminal, "nada" means "nothing
}

```
Hope everything is correct here, once again, not even sure if this still works after the last time i touched it...

**Comment by Lxy85** [comment]
Thank you very much. Best wishes for you.













At 2022-01-11 21:05:22, "Sophia Cristina" ***@***.***> wrote:

Ohh, i see, this one?:
Artelnics/opennn#150

I have changed part of that code, however, long time i don't mess with OpenNN since i think it can't do GAN, so i would have to do everything manually. I still think i may use their convolution and other layers...
Consequently, i'm not even sure if my code still works...

The code is a mess, and it is almost a "hello world" of it... Also, i'm still a "total" noob on OpenNN, i saw you opened an issue there too, however, i don't know how to deal with the dataset and Tensor object.
I hope you find your solution, in my case it was just that the DataSet, for some reason, needs at least TWO inputs, and when i was using only one input for test, it was crashing...

Anyway, my code is below, i deleted some headers which aren't useful for you, however, i'm going to add some of the functions i had inside it being used:

// CREATE A DATASET FROM PATHS FOR A RANGE OF IMAGES BASED ON THE SIZE OF A VECTOR OF TARGETS: // Create a bunch of images like 'image0.png', write 'Prefix = image'. // It always begins at '0', if you want a specific image, skew this code. // Target vector size must be <= amount of available images at path. void MakeDataSetRGBLine(string Prefix, vector<int> Target) { ofstream oPrint("DATA.csv"); if (!oPrint.is_open()) { cout << "!!! Arquivo não foi aberto. !!!" << endl; } else { if (Target.size() > 0) { for (int Index = 0; Index < Target.size(); ++Index) { CImg<unsigned char> BMP(Str2Char(Prefix + to_string(Index) + ".png").data()); // Open imagem file. Str2Char is an abandoned function i made to make easier by writing everything between '(' and ')' without creating another string variable, it in fact returns a vector<unsigned char> vector<Point3DFlt> Image = BitmapRGBMatrix(BMP); // FLATTEN RGB values, this method just go from line by line of the image and push back the RGB values to the vector oPrint << Target[Index]; for (int n = 0; n < Image.size(); ++n) { oPrint << "," << Image[n].x << "," << Image[n].y << "," << Image[n].z; } oPrint << endl; } } else { oPrint << "'Target' vector is empty!\n"; std::cout << "'Target' vector is empty!\n"; } } oPrint.close(); }

`void Configure(OpenNN::NeuralNetwork& NN, const Vector<size_t> InputDimensions, const size_t outputs_number)
{
// Scaling layer

ScalingLayer* scaling_layer = new ScalingLayer(InputDimensions);

NN.add_layer(scaling_layer);



const Vector<size_t> scaling_layer_outputs_dimensions = scaling_layer->get_outputs_dimensions();



// Convolutional layer 1



ConvolutionalLayer* convolutional_layer_1 = new ConvolutionalLayer(scaling_layer_outputs_dimensions, { 8, 5, 5 });

NN.add_layer(convolutional_layer_1);



const Vector<size_t> convolutional_layer_1_outputs_dimensions = convolutional_layer_1->get_outputs_dimensions();



// Pooling layer 1



PoolingLayer* pooling_layer_1 = new PoolingLayer(convolutional_layer_1_outputs_dimensions);

NN.add_layer(pooling_layer_1);



const Vector<size_t> pooling_layer_1_outputs_dimensions = pooling_layer_1->get_outputs_dimensions();



// Convolutional layer 2



ConvolutionalLayer* convolutional_layer_2 = new ConvolutionalLayer(pooling_layer_1_outputs_dimensions, { 4, 3, 3 });

NN.add_layer(convolutional_layer_2);



const Vector<size_t> convolutional_layer_2_outputs_dimensions = convolutional_layer_2->get_outputs_dimensions();



// Pooling layer 2



PoolingLayer* pooling_layer_2 = new PoolingLayer(convolutional_layer_2_outputs_dimensions);

NN.add_layer(pooling_layer_2);



const Vector<size_t> pooling_layer_2_outputs_dimensions = pooling_layer_2->get_outputs_dimensions();



// Convolutional layer 3



ConvolutionalLayer* convolutional_layer_3 = new ConvolutionalLayer(pooling_layer_2_outputs_dimensions, { 2, 3, 3 });

NN.add_layer(convolutional_layer_3);



const Vector<size_t> convolutional_layer_3_outputs_dimensions = convolutional_layer_3->get_outputs_dimensions();



// Pooling layer 3



PoolingLayer* pooling_layer_3 = new PoolingLayer(convolutional_layer_3_outputs_dimensions);

NN.add_layer(pooling_layer_3);



const Vector<size_t> pooling_layer_3_outputs_dimensions = pooling_layer_3->get_outputs_dimensions();



// Perceptron layer



PerceptronLayer* perceptron_layer = new PerceptronLayer(pooling_layer_3_outputs_dimensions.calculate_product(), 18);

NN.add_layer(perceptron_layer);



const size_t perceptron_layer_outputs = perceptron_layer->get_neurons_number();



// Probabilistic layer



ProbabilisticLayer* probabilistic_layer = new ProbabilisticLayer(perceptron_layer_outputs, outputs_number);

NN.add_layer(probabilistic_layer);



NN.print_summary();



}
`

`// CImg to help me:
#include "ysxCImg.h"
#include "ysxPrint.h"

// System includes
#include <math.h>
#include <time.h>

// OpenNN includes
#include "../../opennn/opennn.h"

using namespace std;
using namespace OpenNN;

int main()
{
cout << "OpenNN. Attempt to make a GAN." << endl;

// MAKE DATA:

CImg<unsigned char> IMG("TestImages/Number1.png"); // 10x10 image; CImg is a pretty simple image header: http://cimg.eu/

vector<int> Targets;

for (int n = 0; n < 11; ++n) { Targets.push_back(1); } // This looks lame, but it is just for the test

MakeDataSetRGBLine("TestImages/Number", Targets);

size_t Size = IMG.width() * IMG.height() * 3; // Size for inputs, not for image

size_t Width = IMG.width() * 3, Height = IMG.height() * 3; // Width for inputs, not for image

//MakeDataSetRGBMatrix(RGB, 10, 0);



// OPEN DATA:

DataSet data_set("DATA.csv", ',', false);



data_set.set_input();

data_set.set_column_use(0, OpenNN::DataSet::VariableUse::Target);

data_set.numeric_to_categorical(0);

data_set.set_batch_instances_number(5);



const Vector<size_t> inputs_dimensions({ 1, Width, Height }); // It was { 1, 10, 10 }, but as i noticed the MNIST example don't counts all channels, i'm using RGB

const Vector<size_t> targets_dimensions({ 10 }); // From '0 - 9', that is 10 targets

data_set.set_input_variables_dimensions(inputs_dimensions);

data_set.set_target_variables_dimensions(targets_dimensions);



const size_t total_instances = 10; // Change it for the number of instances, i have 10 images in my folder

data_set.set_instances_uses((Vector<string>(total_instances, "Training").assemble(Vector<string>(Size - total_instances, "Unused"))));

data_set.split_instances_random(0.75, 0, 0.25);



// ####### NN #######



NeuralNetwork NN;

Configure(NN, inputs_dimensions, 10);

  

// #####################

// #####################

// #####################

int NADA; cin >> NADA; // Ignore, just a lazy ass trick to pause the terminal, "nada" means "nothing



}`

Hope everything is correct here, once again, not even sure if this still works after the last time i touched it...

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
